console.log("Site designed and developed at Mandelbrot Studio®");
console.log("https://mandelbrot.mx/");
console.log("");
console.log("UI Design: Zero Morales");
console.log("https://www.instagram.com/zero_alex/");
console.log("");
console.log("Front-End Development:");
console.log(" Juan Fuentes");
console.log(" https://www.instagram.com/juanfuent.es/");
console.log(" Andrew Alvarado");
console.log(" https://www.instagram.com/andrew__alva/");